name: Release pipeline

on:
  push:
    branches:
      - refactor

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: bahmutov/npm-install@v1
    - name: Check lint
      run: yarn lint:strict
    - name: Check unit test
      run: yarn test:unit
    - name: Build
      run: yarn build
    - name: Release maybe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run semantic-release
