name: Release pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: bahmutov/npm-install@v1
    - name: Check lint
      run: yarn lint:strict
    - name: Check unit test
      run: yarn test:unit
    - name: Build
      run: yarn build
    - name: Release maybe
    - uses: codfish/semantic-release-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - run: echo $RELEASE_VERSION
