name: Pipeline

on:
  push:
    branches:
      - to-vite2

jobs:
  check-quality-and-deploy-preview:
    runs-on: ubuntu-latest
    name: Check quality and deploy
    steps:
    - uses: actions/checkout@v2
    - uses: bahmutov/npm-install@v1
    - run: yarn --frozen-lockfile

    - name: Check type
      run: yarn type

    - name: Check code
      run: yarn lint

    - name: Check unit test
      run: yarn test:unit

    - name: Build
      run: yarn build

    - name: Deploy to ftp
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        METHOD: sftp
        PORT: ${{ secrets.FTP_PORT }}
        LOCAL_DIR: dist
        REMOTE_DIR: /www/d2-advance/vite2-preview
        ARGS: --delete --verbose --parallel=100
